// web/components/FreeTierLabel.tsx
//
// Engine-tier label rendered on /recommend (Phase 3) and /roadmap
// (Phase 4 Step 6). The engine-name portion is derived server-side
// from the catalog-tracked resolver so the label automatically
// follows the engine when the Phase 9 §9.2 cron flips it.
//
// T3b: /recommend is now tiered. The copy names the ENGINE that generated the
// recommendation (#271) — "Recommendation generated by Gemini 2.5 Pro" for
// signed-in frontier users (no upgrade CTA, since they're already on it), and the
// same line plus an "upgrade for frontier models" CTA otherwise — so it can't be
// mistaken for the recommended model shown in the card header.

import Link from "next/link";

export type FreeTierSurface = "recommend" | "roadmap";

// engine string → display copy. Centralized here so a future
// engine swap is a one-line edit; the resolver returns the model
// id and this map renders its public-facing copy. Unknown
// engines fall back to a neutral label.
const ENGINE_DISPLAY: Record<string, string> = {
  "gemini-2.5-flash": "Gemini 2.5 Flash",
  "gemini-3-flash": "Gemini 3 Flash",
  // T3b signed-in quality-tier engine.
  "gemini-2.5-pro": "Gemini 2.5 Pro",
};

function engineDisplayName(engine: string | undefined): string | null {
  if (!engine) {
    return null;
  }
  return ENGINE_DISPLAY[engine] ?? null;
}

interface FreeTierLabelProps {
  // Phase 3 callers may still pass a fully-formed `label` string; the
  // /roadmap surface passes surface + engine; /recommend passes
  // surface + engine + tier and lets the component format the copy.
  label?: string;
  surface?: FreeTierSurface;
  engine?: string;
  // T3b: which tier served the recommendation. "frontier" → quality-tier
  // label with no upgrade CTA; "free"/undefined → free-tier upgrade copy.
  tier?: "free" | "frontier";
}

function freeTierCopy(engine: string | undefined): string {
  const display = engineDisplayName(engine);
  return display
    ? `Free tier (${display}) — upgrade for frontier models`
    : "Free tier — upgrade for frontier models";
}

export function FreeTierLabel(props: FreeTierLabelProps) {
  const { label, surface, engine, tier } = props;

  // Phase-3 callers pass a fully-formed label string (kept as a /pricing link).
  if (label) {
    return (
      <p className="text-sm">
        <Link
          href="/pricing"
          className="font-medium text-brand-accent underline-offset-2 hover:underline"
        >
          {label}
        </Link>
      </p>
    );
  }

  // /recommend: name the ENGINE that PRODUCED the recommendation, so it can't be
  // mistaken for the recommended model (#271). The recommended model is shown in
  // the card header above; this line is the engine that generated the analysis.
  if (surface === "recommend") {
    const display = engineDisplayName(engine);
    // Name the engine directly — "Recommendation generated by Gemini 2.5 Pro".
    // Fall back to "roadmodel" only when the engine id is unknown/unmapped.
    const by = `Recommendation generated by ${display ?? "roadmodel"}`;
    if (tier === "frontier") {
      return (
        <p className="text-sm text-brand-slate-600 dark:text-brand-slate-300">{by}</p>
      );
    }
    return (
      <p className="text-sm text-brand-slate-600 dark:text-brand-slate-300">
        {by} &mdash;{" "}
        <Link
          href="/pricing"
          className="font-medium text-brand-accent underline-offset-2 hover:underline"
        >
          upgrade for frontier models
        </Link>
      </p>
    );
  }

  // /roadmap (+ fallback): unchanged free-tier upgrade copy.
  return (
    <p className="text-sm">
      <Link
        href="/pricing"
        className="font-medium text-brand-accent underline-offset-2 hover:underline"
      >
        {freeTierCopy(engine)}
      </Link>
    </p>
  );
}
