"""Live, private project context shared by coding agents (stdlib, Python 3.9+).

The project owns the memory directory. Claude's former store redirects there,
so already-open sessions and other agents see the same files. No transcripts,
credentials, permission settings, or private memory enter tracked instructions.
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

BEGIN = "<!-- roadmodel:shared-context:start -->"
END = "<!-- roadmodel:shared-context:end -->"
OLD_MEMORY = "<!-- generated by roadmodel-update from Claude Code auto-memory -->"
PRIVATE = (
    "/.agents/memory.before-roadmodel-*",
    "/.roadmodel/memory/",
    "/.roadmodel/context.json",
    "/.roadmodel/context.py",
    "/.agents/memory.md",
    "/.roadmodel/HANDOFF.md",
    "/.roadmodel/WORKTREE.md",
    "/.roadmodel/worktree_memory.py",
    "/.roadmodel/worktree-imports.json",
    "/.agents/shared-context.md",
    "/.agents/rules/roadmodel-context.md",
    "/AGENTS.override.md",
    "/CLAUDE.local.md",
    "/.claude/settings.local.json",
)


def _git(project: Path, *args: str) -> str:
    result = subprocess.run(  # noqa: S603
        ["git", "-C", str(project), *args],  # noqa: S607
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=30,
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "git command failed")
    return result.stdout.strip()


def _atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".roadmodel-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def _json(path: Path) -> dict:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return data


def _block(text: str, body: str) -> str:
    block = f"{BEGIN}\n{body.rstrip()}\n{END}"
    if BEGIN in text or END in text:
        if text.count(BEGIN) != 1 or text.count(END) != 1:
            raise ValueError("malformed shared-context markers; existing text left intact")
        start, end = text.index(BEGIN), text.index(END)
        if start > end:
            raise ValueError("reversed shared-context markers")
        return text[:start] + block + text[end + len(END) :]
    return text.rstrip() + ("\n\n" if text.strip() else "") + block + "\n"


def _same(a: Path, b: Path) -> bool:
    return os.path.normcase(str(a.resolve())) == os.path.normcase(str(b.resolve()))


def _redirect(path: Path) -> bool:
    # Python 3.9–3.11 is_symlink() does not recognize Windows junctions.
    expected = path.parent.resolve() / path.name
    return path.is_symlink() or os.path.normcase(str(path.resolve())) != os.path.normcase(
        str(expected)
    )


def _files(directory: Path) -> dict[str, str]:
    if not directory.exists():
        return {}
    if not directory.is_dir():
        raise ValueError(f"memory location is not a directory: {directory}")
    result = {}
    for path in sorted(directory.rglob("*")):
        if _redirect(path):
            raise ValueError(f"memory contains a symbolic link; inspect before migration: {path}")
        if path.is_file():
            result[path.relative_to(directory).as_posix()] = hashlib.sha256(
                path.read_bytes()
            ).hexdigest()
    return result


def _link(source: Path, target: Path) -> None:
    """Windows junctions do not require Developer Mode or administrator rights."""
    if os.name != "nt":
        source.symlink_to(target, target_is_directory=True)
        return

    def quote(value: Path) -> str:
        return "'" + str(value).replace("'", "''") + "'"

    command = (
        "$ErrorActionPreference='Stop'; "
        f"New-Item -ItemType Junction -Path {quote(source)} -Target {quote(target)} | Out-Null"
    )
    encoded = base64.b64encode(command.encode("utf-16-le")).decode("ascii")
    subprocess.run(  # noqa: S603
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-EncodedCommand", encoded],  # noqa: S607
        check=True,
        capture_output=True,
        timeout=30,
    )


def _repo(project: Path) -> tuple[Path, Path]:
    root = Path(_git(project, "rev-parse", "--show-toplevel")).resolve()
    common = Path(_git(root, "rev-parse", "--git-common-dir"))
    if not common.is_absolute():
        common = root / common
    common = common.resolve()
    # Worktrees use the main checkout's context. Nonstandard git dirs retain
    # the current root rather than assuming their parent's layout.
    owner = common.parent if common.name == ".git" else root
    return owner, common


def _legacy_memory(project: Path, home: Path) -> Path:
    # Claude replaces every non-alphanumeric character with '-' in the
    # project id (including Windows ':' and repository-name underscores).
    slug = os.environ.get("CLAUDE_CODE_PROJECT_DIR_NAME") or re.sub(
        r"[^a-zA-Z0-9]", "-", str(project.resolve())
    )
    root = Path(os.environ.get("CLAUDE_CONFIG_DIR", str(home / ".claude"))).expanduser()
    return root / "projects" / slug / "memory"


def _source(project: Path, home: Path, target: Path) -> Path:
    value = None
    # Preserve the effective explicit choice before adopting the default.
    config = Path(os.environ.get("CLAUDE_CONFIG_DIR", str(home / ".claude"))).expanduser()
    for file in (
        config / "settings.json",
        project / ".claude/settings.json",
        project / ".claude/settings.local.json",
    ):
        settings = _json(file)
        if settings.get("autoMemoryDirectory"):
            value = settings["autoMemoryDirectory"]
    if value is not None:
        if not isinstance(value, str):
            raise ValueError("autoMemoryDirectory must be a path string")
        path = Path(value.replace("~/", str(home) + "/", 1)).expanduser()
        if not path.is_absolute():
            raise ValueError("autoMemoryDirectory must be absolute")
        return path
    return _legacy_memory(project, home)


def _adopt(source: Path, target: Path) -> None:
    if _same(source, target):
        target.mkdir(parents=True, exist_ok=True)
        return
    if _redirect(source):
        raise ValueError(f"existing memory redirect has a different target: {source}")
    if source.resolve() in target.resolve().parents or target.resolve() in source.resolve().parents:
        raise ValueError("memory source and destination overlap; originals preserved")
    if _redirect(target):
        raise ValueError("memory destination is already a redirect to another store")
    before = _files(source)
    existing = _files(target)
    conflicts = [
        name for name, digest in before.items() if name in existing and existing[name] != digest
    ]
    if conflicts:
        raise ValueError(
            "memory migration conflict (both copies preserved): " + ", ".join(conflicts)
        )
    target.mkdir(parents=True, exist_ok=True)
    for name in before:
        dest = target / name
        if not dest.exists():
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source / name, dest)
    if _files(source) != before:
        raise ValueError("Claude memory changed during migration; retry, originals preserved")
    copied = _files(target)
    if any(copied.get(name) != digest for name, digest in before.items()):
        raise ValueError("copied memory failed verification; originals preserved")
    if not source.exists():
        source.parent.mkdir(parents=True, exist_ok=True)
        _link(source, target)
        return
    backup = source.with_name(
        "memory.before-roadmodel-" + dt.datetime.now().strftime("%Y%m%d%H%M%S%f")
    )
    source.rename(backup)
    try:
        if _files(backup) != before:
            raise ValueError("Claude memory changed during migration; retry, originals preserved")
        _link(source, target)
    except Exception:
        backup.rename(source)
        raise
    # Keep a complete backup next to Claude's former store. Never discard it.


def _instruction_body() -> str:
    return """## Shared rules, memory, and handoff

Read the project's `AGENTS.md` in full when present; this local adapter
supplements it. Read large instruction files in chunks rather than silently
truncating them. Their directory scopes and precedence still apply.

At session start, from the repository root run `python .roadmodel/context.py --session` (use `python3`
or `py -3` if needed). This is a local, deterministic freshness check; it
does not call an AI or upgrade packages. Report a failure and inspect the
named files before relying on stale context. If this checkout has not been
set up yet, run the installed `roadmodel-upgrade` skill.

Read `.roadmodel/context.json`, the live `.roadmodel/memory/MEMORY.md` index,
`.roadmodel/HANDOFF.md`, and `.roadmodel/WORKTREE.md`. Read relevant full memory
entries from `.roadmodel/memory/`; the context manifest lists every entry,
including ones absent from the index. Never treat a missing summary as a
missing fact. These personal files are git-excluded; use shell reads when
an editor file tool hides ignored files.
When `memory/worktrees/INDEX.md` exists, consult its provenance and relevant
worktree memories too; their paths are relative to `.roadmodel/`.

Also read this repository's `CLAUDE.md`, `.claude/CLAUDE.md`, and
`CLAUDE.local.md` when present. Enumerate `.claude/rules/**/*.md`; preserve
each rule's path scope and follow its referenced files when applicable.
Before editing a subdirectory, read the governing ancestor and directory
`CLAUDE.md`, `.claude/CLAUDE.md`, and `.claude/rules/` files as well.
Client-specific tool, hook, and permission settings retain their native
meaning; do not translate them into blanket permission grants.

Every agent records durable decisions in the same `.roadmodel/memory/`
directory and updates its `MEMORY.md` index. Before ending or switching
agents, update `.roadmodel/HANDOFF.md` with the current objective, branch,
changes, validation, unresolved decisions, and next action. Re-read these
files after another agent works on the project. Preserve concurrent edits
and resolve conflicts explicitly. Never commit personal memory or handoffs.
"""


def _worktrees(
    project: Path, home: Path, *, dry_run: bool = False, check: bool = False
) -> tuple[list[str], bool]:
    path = Path(__file__).with_name("worktree_memory.py")
    spec = importlib.util.spec_from_file_location("roadmodel_worktree_memory", path)
    if spec is None or spec.loader is None or not path.is_file():
        raise ValueError("worktree memory helper is missing; run roadmodel-upgrade")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    exec(compile(path.read_bytes(), str(path), "exec"), module.__dict__)  # noqa: S102
    return module.import_worktree_memory(project, home, dry_run=dry_run, check=check)


def _snapshot(project: Path) -> str:
    branch = _git(project, "branch", "--show-current") or "(detached HEAD)"
    head = _git(project, "rev-parse", "HEAD")
    changes = _git(project, "status", "--short") or "(clean)"
    commits = _git(project, "log", "-5", "--format=%h %s")
    roadmaps = sorted(
        {
            str(p.relative_to(project))
            for pattern in (
                "private/*roadmap*.md",
                "private/ROADMAP.md",
                "docs/roadmap/*.md",
                "ROADMAP.md",
            )
            for p in project.glob(pattern)
        }
    )
    return (
        f"# Worktree at session start\n\nBranch: `{branch}`\nHEAD: `{head}`\n\n"
        f"## Working changes\n\n```text\n{changes}\n```\n\n"
        f"## Recent commits\n\n```text\n{commits}\n```\n\n"
        "## Roadmaps to consult\n\n"
        + "\n".join(f"- `{p}`" for p in roadmaps)
        + "\n\nThis is a filesystem snapshot, not a claim that a roadmap step is complete.\n"
        "The handoff records intent and unresolved decisions that Git cannot infer.\n"
    )


def _manifest(project: Path, target: Path, source: Path) -> dict:
    files = _files(target)
    return {
        "schema": 1,
        "project": str(project),
        "memory": str(target),
        "claude_memory": str(source),
        "entries": files,
        "rules": {
            str(p.relative_to(project)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(
                set(
                    [
                        project / "AGENTS.md",
                        project / "AGENTS.override.md",
                        project / "CLAUDE.md",
                        project / ".claude/CLAUDE.md",
                        project / "CLAUDE.local.md",
                    ]
                    + list((project / ".claude/rules").rglob("*.md"))
                )
            )
            if p.is_file()
        },
        "handoff": ".roadmodel/HANDOFF.md",
    }


def sync_project(
    project: Path, home: Optional[Path] = None, *, dry_run: bool = False, check: bool = False
) -> tuple[list[str], bool]:
    """Install/verify shared context. Never run Git mutations or a model."""
    home = home or Path.home()
    project = project.resolve()
    lines: list[str] = []
    try:
        owner, git_dir = _repo(project)
        target = owner / ".roadmodel/memory"
        source = _source(owner, home, target)
        # A deliberately configured custom store remains authoritative. Do
        # not relocate a store that may be shared with other repositories.
        if not _same(source, target) and not _same(source, _legacy_memory(owner, home)):
            target = source
        saved = _json(project / ".roadmodel/context.json") or _json(
            project / ".agents/context.json"
        )
        origin = Path(saved.get("claude_memory", str(source)))
        if saved and not _same(origin, source):
            raise ValueError("previous Claude memory redirect changed; inspect before repairing")
        before = _files(source)
        _files(target)
        agents = project / "AGENTS.override.md"
        original = agents.read_text(encoding="utf-8") if agents.exists() else ""
        updated = _block(original, _instruction_body())
        claude = project / "CLAUDE.local.md"
        claude_original = claude.read_text(encoding="utf-8") if claude.exists() else ""
        imports = "@.agents/shared-context.md"
        if (project / "AGENTS.md").exists():
            imports = "@AGENTS.md\n\n" + imports
        claude_updated = _block(claude_original, imports)
        shared_body = _instruction_body().rstrip() + "\n"
        rule = project / ".agents/rules/roadmodel-context.md"
        rule_body = "---\ntrigger: always_on\n---\n\n" + shared_body
        drift: list[str] = []
        if original != updated:
            drift.append("Codex shared-context adapter")
        if claude_original != claude_updated:
            drift.append("Claude shared-instructions import")
        for path, content in (
            (project / ".agents/shared-context.md", shared_body),
            (rule, rule_body),
        ):
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(project)))
        settings_path = owner / ".claude/settings.local.json"
        settings = _json(settings_path)
        if settings.get("autoMemoryDirectory") != str(target):
            drift.append("Claude shared memory setting")
        if not target.is_dir() or not _same(source, target):
            drift.append("live memory directory/redirect")
        if not (project / ".roadmodel/memory").is_dir() or not _same(
            project / ".roadmodel/memory", target
        ):
            drift.append("project memory alias")
        if project != owner and _json(project / ".claude/settings.local.json").get(
            "autoMemoryDirectory"
        ) != str(target):
            drift.append("worktree Claude shared memory setting")
        for relative in (
            ".roadmodel/context.json",
            ".roadmodel/context.py",
            ".roadmodel/HANDOFF.md",
        ):
            if not (project / relative).exists():
                drift.append(relative)
        for installed, shipped in (
            ("context.py", "agent_context.py"),
            ("worktree_memory.py", "worktree_memory.py"),
        ):
            helper = project / ".roadmodel" / installed
            expected = (
                Path(__file__)
                if shipped == "agent_context.py"
                else Path(__file__).with_name(shipped)
            )
            # Installation writes LF text. Windows Git checkouts may supply
            # CRLF source files, which are the same helper version.
            if not helper.exists() or helper.read_text(encoding="utf-8") != expected.read_text(
                encoding="utf-8"
            ):
                drift.append(f"session helper version: {installed}")
        exclude = git_dir / "info/exclude"
        old_exclude = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
        missing = [p for p in PRIVATE if p not in old_exclude.splitlines()]
        if missing:
            drift.append("private context Git exclusions")
        # Never silently keep personal memory in the index, even if ignored.
        tracked = _git(project, "ls-files", "--", *(p.strip("/") for p in PRIVATE))
        if tracked:
            raise ValueError(
                "personal context is tracked; remove from Git before syncing: "
                + tracked.replace("\n", ", ")
            )
        if check:
            if drift:
                return ["context: DRIFT: " + "; ".join(drift)], False
            worktree_lines, worktree_ok = _worktrees(owner, home, check=True)
            actual = _manifest(project, target, origin)
            changed = saved != actual
            lines.append(
                f"context: {'fresh content available (session refresh required)' if changed else 'verified'}; {len(actual['entries'])} complete memory files"
            )
            return lines + worktree_lines, not changed and worktree_ok
        if dry_run:
            worktree_lines, worktree_ok = _worktrees(owner, home, dry_run=True)
            return [
                "context: would repair " + "; ".join(drift) if drift else "context: configured",
                f"memory: {len(before)} files, full bodies retained",
            ] + worktree_lines, worktree_ok
        # Install ignores before creating personal files. Worktree common
        # excludes protect both the current and main checkout.
        if missing:
            _atomic(
                exclude,
                old_exclude.rstrip()
                + "\n\n# roadmodel private agent context\n"
                + "\n".join(missing)
                + "\n",
            )
        _adopt(source, target)
        if not (target / "MEMORY.md").exists():
            _atomic(
                target / "MEMORY.md",
                "# Shared project memory\n\nRecord durable decisions here and link detailed entries.\n",
            )
        settings["autoMemoryDirectory"] = str(target)
        _atomic(settings_path, json.dumps(settings, indent=2) + "\n")
        if original != updated:
            _atomic(agents, updated)
        if claude_original != claude_updated:
            _atomic(claude, claude_updated)
        _atomic(project / ".agents/shared-context.md", shared_body)
        _atomic(rule, rule_body)
        # A real worktree's per-project path redirects to the shared owner.
        local_memory = project / ".roadmodel/memory"
        if not _same(local_memory, target):
            if local_memory.exists():
                raise ValueError("worktree already has separate memory; reconcile it explicitly")
            local_memory.parent.mkdir(parents=True, exist_ok=True)
            _link(local_memory, target)
        if project != owner:
            local_settings = _json(project / ".claude/settings.local.json")
            local_settings["autoMemoryDirectory"] = str(target)
            _atomic(
                project / ".claude/settings.local.json", json.dumps(local_settings, indent=2) + "\n"
            )
        handoff = project / ".roadmodel/HANDOFF.md"
        if not handoff.exists():
            _atomic(
                handoff,
                "# Agent handoff\n\nNo narrative handoff has been recorded yet. Read WORKTREE.md, the live\nmemory index, and the project's current roadmap before continuing.\n\n## Current objective\n\n## Changes and validation\n\n## Unresolved decisions and next action\n",
            )
        _atomic(project / ".roadmodel/WORKTREE.md", _snapshot(project))
        _atomic(project / ".roadmodel/context.py", Path(__file__).read_text(encoding="utf-8"))
        _atomic(
            project / ".roadmodel/worktree_memory.py",
            Path(__file__).with_name("worktree_memory.py").read_text(encoding="utf-8"),
        )
        worktree_lines, worktree_ok = _worktrees(owner, home)
        lines.extend(worktree_lines)
        manifest = _manifest(project, target, origin)
        _atomic(project / ".roadmodel/context.json", json.dumps(manifest, indent=2) + "\n")
        legacy_export = project / ".agents/memory.md"
        if not legacy_export.exists() or legacy_export.read_text(encoding="utf-8").startswith(
            OLD_MEMORY
        ):
            _atomic(
                legacy_export,
                OLD_MEMORY
                + "\n# Live shared memory\n\nRead `../.roadmodel/memory/MEMORY.md` and the full entries beside it.\nThis directory is shared with Claude Code and every configured agent.\nRead `../.roadmodel/context.json` for the complete inventory and `../.roadmodel/HANDOFF.md` for work in progress.\n",
            )
        lines.append(
            f"context: ready; {len(manifest['entries'])} complete memory files; live shared directory"
        )
        lines.append("handoff: preserved; worktree snapshot refreshed")
        return lines, worktree_ok
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        return [f"context: FAILED: {exc}"], False


def session(project: Path) -> tuple[list[str], bool]:
    """Refresh inventories/snapshot only; do not migrate stores at startup."""
    try:
        project = project.resolve()
        saved = _json(project / ".roadmodel/context.json")
        if saved.get("schema") != 1 or not saved.get("memory"):
            raise ValueError("shared context is not installed; run roadmodel-upgrade")
        target = Path(saved["memory"])
        if not target.is_dir() or not _same(project / ".roadmodel/memory", target):
            raise ValueError("shared memory is missing or its redirect changed")
        # A redirect and auto-memory setting are both checked: files merely
        # existing does not establish that Claude uses the same store.
        source = Path(saved["claude_memory"])
        if not _same(source, target):
            raise ValueError("Claude's memory redirect no longer targets shared memory")
        settings = _json(project / ".claude/settings.local.json")
        if settings.get("autoMemoryDirectory") != str(target):
            raise ValueError("Claude's shared-memory setting changed")
        instructions = (project / "AGENTS.override.md").read_text(encoding="utf-8")
        if BEGIN not in instructions or END not in instructions:
            raise ValueError("shared instruction adapter is missing")
        owner, _ = _repo(project)
        worktree_lines, worktree_ok = _worktrees(owner, Path.home())
        if not worktree_ok:
            return worktree_lines, False
        current = _manifest(project, target, source)
        changed = saved != current
        _atomic(project / ".roadmodel/context.json", json.dumps(current, indent=2) + "\n")
        _atomic(project / ".roadmodel/WORKTREE.md", _snapshot(project))
        digest = hashlib.sha256(json.dumps(current, sort_keys=True).encode()).hexdigest()[:12]
        return worktree_lines + [
            f"Shared context {'refreshed' if changed else 'verified'}: {len(current['entries'])} complete memory files; revision {digest}.",
            "Read .roadmodel/memory/MEMORY.md and .roadmodel/HANDOFF.md before work; full entries are in .roadmodel/memory/.",
        ], True
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        return [f"Shared context FAILED: {exc}"], False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument(
        "--session", action="store_true", help="refresh live inventory and worktree snapshot"
    )
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    lines, ok = (
        session(args.project)
        if args.session
        else sync_project(args.project, check=args.check, dry_run=args.dry_run)
    )
    for line in lines:
        print(line)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
