// web/app/terms/page.tsx
import Link from "next/link";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Terms — roadmodel",
  description: "Terms of use for the anonymous roadmodel.ai recommender.",
};

const ARCFORGE_URL = "https://arcforgelabs.io";
const REPO_URL = "https://github.com/nathanramoscfa/roadmodel";

export default function TermsPage() {
  return (
    <>
      <article className="mx-auto max-w-2xl px-6 py-16 sm:py-20">
        <p className="text-sm font-semibold uppercase tracking-wide text-brand-accent">
          roadmodel
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-brand-slate-900 sm:text-4xl">
          Terms of Use
        </h1>
        <p className="mt-2 text-sm text-brand-slate-500">
          Last updated: 2026-05-20.
        </p>

        <div className="prose prose-slate mt-8 max-w-none text-brand-slate-700">
          <p>
            <strong>roadmodel.ai</strong> is an anonymous AI model-recommendation
            service operated by Arcforge Digital Labs LLC. By using the site
            you agree to the terms below.
          </p>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            Service
          </h2>
          <p className="mt-3">
            roadmodel.ai recommends an AI model, platform, and settings for a
            task you describe. Recommendations are generated by third-party
            large language models and may be incorrect, incomplete, or out of
            date. You use recommendations <strong>at your own risk</strong>.
            The service is provided &ldquo;as is&rdquo;, without warranty of
            any kind, express or implied, including warranties of
            merchantability or fitness for a particular purpose. Verify any
            recommendation against current model documentation before acting
            on it.
          </p>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            Fair use
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              The free recommendation endpoint is rate-limited to 3 requests
              per day per anonymized IP+UA hash, with a 10-per-minute burst
              cap.
            </li>
            <li>
              Attempts to circumvent these limits — including IP rotation,
              distributed clients, automation at scale, or other abuse — are
              prohibited and may result in IP-level blocks.
            </li>
            <li>
              Do not submit content that is illegal, infringing, or designed
              to elicit harmful output. We may refuse service for any reason.
            </li>
          </ul>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            No account, no data-subject relationship
          </h2>
          <p className="mt-3">
            We don&rsquo;t ask for an account. We don&rsquo;t ask for personal
            information. We store only what is described on the{" "}
            <Link
              href="/privacy"
              className="text-brand-accent hover:underline"
            >
              Privacy
            </Link>{" "}
            page (salted hashes of identifiers and per-request metadata).
          </p>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            Intellectual property
          </h2>
          <p className="mt-3">
            roadmodel.ai branding and original site content are &copy; 2026
            Arcforge Digital Labs LLC. The underlying recommendation logic is
            open source under the license in the{" "}
            <Link
              href={REPO_URL}
              className="text-brand-accent hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              project repository
            </Link>
            .
          </p>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            Changes
          </h2>
          <p className="mt-3">
            We may update these terms. The &ldquo;Last updated&rdquo; date
            above will move. Continued use after a change constitutes
            acceptance.
          </p>

          <h2 className="mt-8 text-xl font-semibold text-brand-slate-900">
            Contact
          </h2>
          <p className="mt-3">
            <Link
              href={ARCFORGE_URL}
              className="text-brand-accent hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              arcforgelabs.io
            </Link>
          </p>
        </div>
      </article>
      <Footer />
    </>
  );
}
